### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by 4meta5** [OpenZeppelin/polkadot-runtime-wrappers#16]
Ideally CI would verify that the macros output valid Rust code. Compiling the crate itself is not as helpful because it does not tell us if the macro expansion is valid Rust.

Note that this ideal may first require #8 because most of our macro output isn't valid Rust until deps include all that are required.

**Comment by ggonzalez94** [comment]
@4meta5 we could add a step that expands the macros(but I think we will need tests or examples for this to be useful)

```
- name: Expand macros
      run: cargo expand 
```

Aditionally we could `trybuild` for testing
WDYT?

**Comment by ggonzalez94** [comment]
I created #18 since I wasn't sure what to add for verifying the macro itself, but if we are happy with this we can close the issues with #19

**Comment by ggonzalez94** [comment]
Marking this as closed in favor of #18. If we find things we need to add specific to macros we can come back and reopen this.
