### ISSUE TITLE
Clean code comments in macro expansion (from templates)

### ISSUE THREAD

**Issue by peektism** [OpenZeppelin/polkadot-runtime-wrappers#24]
Raised during review of #1

**Comment by mittal-parth** [comment]
Hi @4meta5, I can help with this.

Just to make sure we need to address the inline documentation as mentioned in [this comment](https://github.com/OpenZeppelin/polkadot-runtime-wrappers/pull/1#discussion_r1824689869).

Also, do you want me to wait for you to merge the existing changes in #1 before proceeding with this?

Thanks!

**Comment by KitHat** [comment]
Hi @mittal-parth!
We are currently in process of creating an RC.
If you can wait until we create an RC and after that resolve this issue targeting `main` branch, we would be really grateful :)

**Comment by mittal-parth** [comment]
Alright noted. I’ll wait :)

**Comment by KitHat** [comment]
I expect RC to be ready in a couple of days max. As soon as #1 and #21  are merged it would be a good point to branch this issue :)

**Comment by mittal-parth** [comment]
Hi @KitHat!

I think this issue can be closed now seeing that the changes have been implemented in [this commit](https://github.com/OpenZeppelin/polkadot-runtime-wrappers/pull/1/commits/a3f96f68cca4238f05beb32d5c5fbe0c24bdb015)?

**Comment by mittal-parth** [comment]
Hi @4meta5 @KitHat!

Started working on this in #47 

I have currently made a draft PR with changes for just one group. If that looks good, I can continue the same for others. The comments have been referenced from `polkadot-sdk`.

Thanks!
